# age=int(input('How old are you?'))
# print('you were born in the year ' , 2024-age)
# # print(f'you were born in the year {born_in} ' )
age=int (input('hou old are you \n'))
print('you were porn in' ,2023-age)